import type { Surah } from '@/types';

/**
 * Complete list of all 114 Surahs with metadata
 */
export const SURAHS: Surah[] = [
    { number: 1, name: 'Al-Fatihah', arabicName: 'الفاتحة', englishName: 'The Opening', englishNameTranslation: 'The Opening', numberOfAyahs: 7, revelationType: 'Meccan' },
    { number: 2, name: 'Al-Baqarah', arabicName: 'البقرة', englishName: 'The Cow', englishNameTranslation: 'The Cow', numberOfAyahs: 286, revelationType: 'Medinan' },
    { number: 3, name: 'Aali Imran', arabicName: 'آل عمران', englishName: 'The Family of Imran', englishNameTranslation: 'The Family of Imran', numberOfAyahs: 200, revelationType: 'Medinan' },
    { number: 4, name: 'An-Nisa', arabicName: 'النساء', englishName: 'The Women', englishNameTranslation: 'The Women', numberOfAyahs: 176, revelationType: 'Medinan' },
    { number: 5, name: 'Al-Ma\'idah', arabicName: 'المائدة', englishName: 'The Table Spread', englishNameTranslation: 'The Table', numberOfAyahs: 120, revelationType: 'Medinan' },
    { number: 6, name: 'Al-An\'am', arabicName: 'الأنعام', englishName: 'The Cattle', englishNameTranslation: 'The Cattle', numberOfAyahs: 165, revelationType: 'Meccan' },
    { number: 7, name: 'Al-A\'raf', arabicName: 'الأعراف', englishName: 'The Heights', englishNameTranslation: 'The Heights', numberOfAyahs: 206, revelationType: 'Meccan' },
    { number: 8, name: 'Al-Anfal', arabicName: 'الأنفال', englishName: 'The Spoils of War', englishNameTranslation: 'The Spoils of War', numberOfAyahs: 75, revelationType: 'Medinan' },
    { number: 9, name: 'At-Tawbah', arabicName: 'التوبة', englishName: 'The Repentance', englishNameTranslation: 'The Repentance', numberOfAyahs: 129, revelationType: 'Medinan' },
    { number: 10, name: 'Yunus', arabicName: 'يونس', englishName: 'Jonah', englishNameTranslation: 'Jonah', numberOfAyahs: 109, revelationType: 'Meccan' },
    { number: 11, name: 'Hud', arabicName: 'هود', englishName: 'Hud', englishNameTranslation: 'Hud', numberOfAyahs: 123, revelationType: 'Meccan' },
    { number: 12, name: 'Yusuf', arabicName: 'يوسف', englishName: 'Joseph', englishNameTranslation: 'Joseph', numberOfAyahs: 111, revelationType: 'Meccan' },
    { number: 13, name: 'Ar-Ra\'d', arabicName: 'الرعد', englishName: 'The Thunder', englishNameTranslation: 'The Thunder', numberOfAyahs: 43, revelationType: 'Medinan' },
    { number: 14, name: 'Ibrahim', arabicName: 'ابراهيم', englishName: 'Abraham', englishNameTranslation: 'Abraham', numberOfAyahs: 52, revelationType: 'Meccan' },
    { number: 15, name: 'Al-Hijr', arabicName: 'الحجر', englishName: 'The Rocky Tract', englishNameTranslation: 'The Rocky Tract', numberOfAyahs: 99, revelationType: 'Meccan' },
    { number: 16, name: 'An-Nahl', arabicName: 'النحل', englishName: 'The Bee', englishNameTranslation: 'The Bee', numberOfAyahs: 128, revelationType: 'Meccan' },
    { number: 17, name: 'Al-Isra', arabicName: 'الإسراء', englishName: 'The Night Journey', englishNameTranslation: 'The Night Journey', numberOfAyahs: 111, revelationType: 'Meccan' },
    { number: 18, name: 'Al-Kahf', arabicName: 'الكهف', englishName: 'The Cave', englishNameTranslation: 'The Cave', numberOfAyahs: 110, revelationType: 'Meccan' },
    { number: 19, name: 'Maryam', arabicName: 'مريم', englishName: 'Mary', englishNameTranslation: 'Mary', numberOfAyahs: 98, revelationType: 'Meccan' },
    { number: 20, name: 'Ta-Ha', arabicName: 'طه', englishName: 'Ta-Ha', englishNameTranslation: 'Ta-Ha', numberOfAyahs: 135, revelationType: 'Meccan' },
    { number: 21, name: 'Al-Anbiya', arabicName: 'الأنبياء', englishName: 'The Prophets', englishNameTranslation: 'The Prophets', numberOfAyahs: 112, revelationType: 'Meccan' },
    { number: 22, name: 'Al-Hajj', arabicName: 'الحج', englishName: 'The Pilgrimage', englishNameTranslation: 'The Pilgrimage', numberOfAyahs: 78, revelationType: 'Medinan' },
    { number: 23, name: 'Al-Mu\'minun', arabicName: 'المؤمنون', englishName: 'The Believers', englishNameTranslation: 'The Believers', numberOfAyahs: 118, revelationType: 'Meccan' },
    { number: 24, name: 'An-Nur', arabicName: 'النور', englishName: 'The Light', englishNameTranslation: 'The Light', numberOfAyahs: 64, revelationType: 'Medinan' },
    { number: 25, name: 'Al-Furqan', arabicName: 'الفرقان', englishName: 'The Criterion', englishNameTranslation: 'The Criterion', numberOfAyahs: 77, revelationType: 'Meccan' },
    { number: 26, name: 'Ash-Shu\'ara', arabicName: 'الشعراء', englishName: 'The Poets', englishNameTranslation: 'The Poets', numberOfAyahs: 227, revelationType: 'Meccan' },
    { number: 27, name: 'An-Naml', arabicName: 'النمل', englishName: 'The Ant', englishNameTranslation: 'The Ant', numberOfAyahs: 93, revelationType: 'Meccan' },
    { number: 28, name: 'Al-Qasas', arabicName: 'القصص', englishName: 'The Stories', englishNameTranslation: 'The Stories', numberOfAyahs: 88, revelationType: 'Meccan' },
    { number: 29, name: 'Al-Ankabut', arabicName: 'العنكبوت', englishName: 'The Spider', englishNameTranslation: 'The Spider', numberOfAyahs: 69, revelationType: 'Meccan' },
    { number: 30, name: 'Ar-Rum', arabicName: 'الروم', englishName: 'The Romans', englishNameTranslation: 'The Romans', numberOfAyahs: 60, revelationType: 'Meccan' },
    { number: 31, name: 'Luqman', arabicName: 'لقمان', englishName: 'Luqman', englishNameTranslation: 'Luqman', numberOfAyahs: 34, revelationType: 'Meccan' },
    { number: 32, name: 'As-Sajdah', arabicName: 'السجدة', englishName: 'The Prostration', englishNameTranslation: 'The Prostration', numberOfAyahs: 30, revelationType: 'Meccan' },
    { number: 33, name: 'Al-Ahzab', arabicName: 'الأحزاب', englishName: 'The Combined Forces', englishNameTranslation: 'The Clans', numberOfAyahs: 73, revelationType: 'Medinan' },
    { number: 34, name: 'Saba', arabicName: 'سبإ', englishName: 'Sheba', englishNameTranslation: 'Sheba', numberOfAyahs: 54, revelationType: 'Meccan' },
    { number: 35, name: 'Fatir', arabicName: 'فاطر', englishName: 'The Originator', englishNameTranslation: 'The Originator', numberOfAyahs: 45, revelationType: 'Meccan' },
    { number: 36, name: 'Ya-Sin', arabicName: 'يس', englishName: 'Ya-Sin', englishNameTranslation: 'Ya-Sin', numberOfAyahs: 83, revelationType: 'Meccan' },
    { number: 37, name: 'As-Saffat', arabicName: 'الصافات', englishName: 'Those Ranges in Ranks', englishNameTranslation: 'Those Ranges in Ranks', numberOfAyahs: 182, revelationType: 'Meccan' },
    { number: 38, name: 'Sad', arabicName: 'ص', englishName: 'Sad', englishNameTranslation: 'Sad', numberOfAyahs: 88, revelationType: 'Meccan' },
    { number: 39, name: 'Az-Zumar', arabicName: 'الزمر', englishName: 'The Groups', englishNameTranslation: 'The Groups', numberOfAyahs: 75, revelationType: 'Meccan' },
    { number: 40, name: 'Ghafir', arabicName: 'غافر', englishName: 'The Forgiver', englishNameTranslation: 'The Forgiver', numberOfAyahs: 85, revelationType: 'Meccan' },
    { number: 41, name: 'Fussilat', arabicName: 'فصلت', englishName: 'Explained in Detail', englishNameTranslation: 'Explained in Detail', numberOfAyahs: 54, revelationType: 'Meccan' },
    { number: 42, name: 'Ash-Shura', arabicName: 'الشورى', englishName: 'The Consultation', englishNameTranslation: 'The Consultation', numberOfAyahs: 53, revelationType: 'Meccan' },
    { number: 43, name: 'Az-Zukhruf', arabicName: 'الزخرف', englishName: 'The Gold Adornments', englishNameTranslation: 'The Gold Adornments', numberOfAyahs: 89, revelationType: 'Meccan' },
    { number: 44, name: 'Ad-Dukhan', arabicName: 'الدخان', englishName: 'The Smoke', englishNameTranslation: 'The Smoke', numberOfAyahs: 59, revelationType: 'Meccan' },
    { number: 45, name: 'Al-Jathiyah', arabicName: 'الجاثية', englishName: 'The Kneeling', englishNameTranslation: 'The Kneeling', numberOfAyahs: 37, revelationType: 'Meccan' },
    { number: 46, name: 'Al-Ahqaf', arabicName: 'الأحقاف', englishName: 'The Wind-Curved Sandhills', englishNameTranslation: 'The Curved Sand-hills', numberOfAyahs: 35, revelationType: 'Meccan' },
    { number: 47, name: 'Muhammad', arabicName: 'محمد', englishName: 'Muhammad', englishNameTranslation: 'Muhammad', numberOfAyahs: 38, revelationType: 'Medinan' },
    { number: 48, name: 'Al-Fath', arabicName: 'الفتح', englishName: 'The Victory', englishNameTranslation: 'The Victory', numberOfAyahs: 29, revelationType: 'Medinan' },
    { number: 49, name: 'Al-Hujurat', arabicName: 'الحجرات', englishName: 'The Rooms', englishNameTranslation: 'The Dwellings', numberOfAyahs: 18, revelationType: 'Medinan' },
    { number: 50, name: 'Qaf', arabicName: 'ق', englishName: 'Qaf', englishNameTranslation: 'Qaf', numberOfAyahs: 45, revelationType: 'Meccan' },
    { number: 51, name: 'Adh-Dhariyat', arabicName: 'الذاريات', englishName: 'The Wind that Scatter', englishNameTranslation: 'The Scatterers', numberOfAyahs: 60, revelationType: 'Meccan' },
    { number: 52, name: 'At-Tur', arabicName: 'الطور', englishName: 'The Mount', englishNameTranslation: 'The Mount', numberOfAyahs: 49, revelationType: 'Meccan' },
    { number: 53, name: 'An-Najm', arabicName: 'النجم', englishName: 'The Star', englishNameTranslation: 'The Star', numberOfAyahs: 62, revelationType: 'Meccan' },
    { number: 54, name: 'Al-Qamar', arabicName: 'القمر', englishName: 'The Moon', englishNameTranslation: 'The Moon', numberOfAyahs: 55, revelationType: 'Meccan' },
    { number: 55, name: 'Ar-Rahman', arabicName: 'الرحمن', englishName: 'The Most Merciful', englishNameTranslation: 'The Most Gracious', numberOfAyahs: 78, revelationType: 'Medinan' },
    { number: 56, name: 'Al-Waqi\'ah', arabicName: 'الواقعة', englishName: 'The Event', englishNameTranslation: 'The Event', numberOfAyahs: 96, revelationType: 'Meccan' },
    { number: 57, name: 'Al-Hadid', arabicName: 'الحديد', englishName: 'The Iron', englishNameTranslation: 'The Iron', numberOfAyahs: 29, revelationType: 'Medinan' },
    { number: 58, name: 'Al-Mujadilah', arabicName: 'المجادلة', englishName: 'The Pleading Woman', englishNameTranslation: 'The Pleading', numberOfAyahs: 22, revelationType: 'Medinan' },
    { number: 59, name: 'Al-Hashr', arabicName: 'الحشر', englishName: 'The Exile', englishNameTranslation: 'The Gathering', numberOfAyahs: 24, revelationType: 'Medinan' },
    { number: 60, name: 'Al-Mumtahanah', arabicName: 'الممتحنة', englishName: 'The Examined One', englishNameTranslation: 'The Examined One', numberOfAyahs: 13, revelationType: 'Medinan' },
    { number: 61, name: 'As-Saff', arabicName: 'الصف', englishName: 'The Ranks', englishNameTranslation: 'The Ranks', numberOfAyahs: 14, revelationType: 'Medinan' },
    { number: 62, name: 'Al-Jumu\'ah', arabicName: 'الجمعة', englishName: 'The Friday', englishNameTranslation: 'Friday', numberOfAyahs: 11, revelationType: 'Medinan' },
    { number: 63, name: 'Al-Munafiqun', arabicName: 'المنافقون', englishName: 'The Hypocrites', englishNameTranslation: 'The Hypocrites', numberOfAyahs: 11, revelationType: 'Medinan' },
    { number: 64, name: 'At-Taghabun', arabicName: 'التغابن', englishName: 'The Mutual Loss and Gain', englishNameTranslation: 'The Cheating', numberOfAyahs: 18, revelationType: 'Medinan' },
    { number: 65, name: 'At-Talaq', arabicName: 'الطلاق', englishName: 'The Divorce', englishNameTranslation: 'The Divorce', numberOfAyahs: 12, revelationType: 'Medinan' },
    { number: 66, name: 'At-Tahrim', arabicName: 'التحريم', englishName: 'The Prohibition', englishNameTranslation: 'The Prohibition', numberOfAyahs: 12, revelationType: 'Medinan' },
    { number: 67, name: 'Al-Mulk', arabicName: 'الملك', englishName: 'The Sovereignty', englishNameTranslation: 'The Dominion', numberOfAyahs: 30, revelationType: 'Meccan' },
    { number: 68, name: 'Al-Qalam', arabicName: 'القلم', englishName: 'The Pen', englishNameTranslation: 'The Pen', numberOfAyahs: 52, revelationType: 'Meccan' },
    { number: 69, name: 'Al-Haqqah', arabicName: 'الحاقة', englishName: 'The Inevitable Reality', englishNameTranslation: 'The Inevitable', numberOfAyahs: 52, revelationType: 'Meccan' },
    { number: 70, name: 'Al-Ma\'arij', arabicName: 'المعارج', englishName: 'The Ways of Ascent', englishNameTranslation: 'The Ascending Stairways', numberOfAyahs: 44, revelationType: 'Meccan' },
    { number: 71, name: 'Nuh', arabicName: 'نوح', englishName: 'Noah', englishNameTranslation: 'Noah', numberOfAyahs: 28, revelationType: 'Meccan' },
    { number: 72, name: 'Al-Jinn', arabicName: 'الجن', englishName: 'The Jinn', englishNameTranslation: 'The Jinn', numberOfAyahs: 28, revelationType: 'Meccan' },
    { number: 73, name: 'Al-Muzzammil', arabicName: 'المزمل', englishName: 'The Enshrouded One', englishNameTranslation: 'The Enfolded One', numberOfAyahs: 20, revelationType: 'Meccan' },
    { number: 74, name: 'Al-Muddaththir', arabicName: 'المدثر', englishName: 'The Cloaked One', englishNameTranslation: 'The Cloaked One', numberOfAyahs: 56, revelationType: 'Meccan' },
    { number: 75, name: 'Al-Qiyamah', arabicName: 'القيامة', englishName: 'The Resurrection', englishNameTranslation: 'The Resurrection', numberOfAyahs: 40, revelationType: 'Meccan' },
    { number: 76, name: 'Al-Insan', arabicName: 'الانسان', englishName: 'The Man', englishNameTranslation: 'The Human', numberOfAyahs: 31, revelationType: 'Medinan' },
    { number: 77, name: 'Al-Mursalat', arabicName: 'المرسلات', englishName: 'Those Sent Forth', englishNameTranslation: 'Those Sent Forth', numberOfAyahs: 50, revelationType: 'Meccan' },
    { number: 78, name: 'An-Naba', arabicName: 'النبإ', englishName: 'The Great News', englishNameTranslation: 'The Great News', numberOfAyahs: 40, revelationType: 'Meccan' },
    { number: 79, name: 'An-Nazi\'at', arabicName: 'النازعات', englishName: 'Those Who Pull Out', englishNameTranslation: 'Those Who Pull Out', numberOfAyahs: 46, revelationType: 'Meccan' },
    { number: 80, name: 'Abasa', arabicName: 'عبس', englishName: 'He Frowned', englishNameTranslation: 'He Frowned', numberOfAyahs: 42, revelationType: 'Meccan' },
    { number: 81, name: 'At-Takwir', arabicName: 'التكوير', englishName: 'The Overthrowing', englishNameTranslation: 'The Overthrowing', numberOfAyahs: 29, revelationType: 'Meccan' },
    { number: 82, name: 'Al-Infitar', arabicName: 'الإنفطار', englishName: 'The Cleaving', englishNameTranslation: 'The Cleaving', numberOfAyahs: 19, revelationType: 'Meccan' },
    { number: 83, name: 'Al-Mutaffifin', arabicName: 'المطففين', englishName: 'The Defrauding', englishNameTranslation: 'Those Who Deal in Fraud', numberOfAyahs: 36, revelationType: 'Meccan' },
    { number: 84, name: 'Al-Inshiqaq', arabicName: 'الإنشقاق', englishName: 'The Splitting Asunder', englishNameTranslation: 'The Splitting Asunder', numberOfAyahs: 25, revelationType: 'Meccan' },
    { number: 85, name: 'Al-Buruj', arabicName: 'البروج', englishName: 'The Big Stars', englishNameTranslation: 'The Mansions of the Stars', numberOfAyahs: 22, revelationType: 'Meccan' },
    { number: 86, name: 'At-Tariq', arabicName: 'الطارق', englishName: 'The Night-Comer', englishNameTranslation: 'The Night-Comer', numberOfAyahs: 17, revelationType: 'Meccan' },
    { number: 87, name: 'Al-A\'la', arabicName: 'الأعلى', englishName: 'The Most High', englishNameTranslation: 'The Most High', numberOfAyahs: 19, revelationType: 'Meccan' },
    { number: 88, name: 'Al-Ghashiyah', arabicName: 'الغاشية', englishName: 'The Overwhelming', englishNameTranslation: 'The Overwhelming', numberOfAyahs: 26, revelationType: 'Meccan' },
    { number: 89, name: 'Al-Fajr', arabicName: 'الفجر', englishName: 'The Dawn', englishNameTranslation: 'The Dawn', numberOfAyahs: 30, revelationType: 'Meccan' },
    { number: 90, name: 'Al-Balad', arabicName: 'البلد', englishName: 'The City', englishNameTranslation: 'The City', numberOfAyahs: 20, revelationType: 'Meccan' },
    { number: 91, name: 'Ash-Shams', arabicName: 'الشمس', englishName: 'The Sun', englishNameTranslation: 'The Sun', numberOfAyahs: 15, revelationType: 'Meccan' },
    { number: 92, name: 'Al-Layl', arabicName: 'الليل', englishName: 'The Night', englishNameTranslation: 'The Night', numberOfAyahs: 21, revelationType: 'Meccan' },
    { number: 93, name: 'Ad-Duha', arabicName: 'الضحى', englishName: 'The Forenoon', englishNameTranslation: 'The Forenoon', numberOfAyahs: 11, revelationType: 'Meccan' },
    { number: 94, name: 'Ash-Sharh', arabicName: 'الشرح', englishName: 'The Opening Forth', englishNameTranslation: 'The Opening Forth', numberOfAyahs: 8, revelationType: 'Meccan' },
    { number: 95, name: 'At-Tin', arabicName: 'التين', englishName: 'The Fig', englishNameTranslation: 'The Fig', numberOfAyahs: 8, revelationType: 'Meccan' },
    { number: 96, name: 'Al-Alaq', arabicName: 'العلق', englishName: 'The Clot', englishNameTranslation: 'The Clot', numberOfAyahs: 19, revelationType: 'Meccan' },
    { number: 97, name: 'Al-Qadr', arabicName: 'القدر', englishName: 'The Night of Decree', englishNameTranslation: 'The Night of Decree', numberOfAyahs: 5, revelationType: 'Meccan' },
    { number: 98, name: 'Al-Bayyinah', arabicName: 'البينة', englishName: 'The Clear Evidence', englishNameTranslation: 'The Clear Evidence', numberOfAyahs: 8, revelationType: 'Medinan' },
    { number: 99, name: 'Az-Zalzalah', arabicName: 'الزلزلة', englishName: 'The Earthquake', englishNameTranslation: 'The Earthquake', numberOfAyahs: 8, revelationType: 'Medinan' },
    { number: 100, name: 'Al-Adiyat', arabicName: 'العاديات', englishName: 'The Courser', englishNameTranslation: 'Those That Run', numberOfAyahs: 11, revelationType: 'Meccan' },
    { number: 101, name: 'Al-Qari\'ah', arabicName: 'القارعة', englishName: 'The Striking Hour', englishNameTranslation: 'The Striking Hour', numberOfAyahs: 11, revelationType: 'Meccan' },
    { number: 102, name: 'At-Takathur', arabicName: 'التكاثر', englishName: 'The Piling Up', englishNameTranslation: 'The Piling Up', numberOfAyahs: 8, revelationType: 'Meccan' },
    { number: 103, name: 'Al-Asr', arabicName: 'العصر', englishName: 'The Time', englishNameTranslation: 'The Time', numberOfAyahs: 3, revelationType: 'Meccan' },
    { number: 104, name: 'Al-Humazah', arabicName: 'الهمزة', englishName: 'The Slanderer', englishNameTranslation: 'The Slanderer', numberOfAyahs: 9, revelationType: 'Meccan' },
    { number: 105, name: 'Al-Fil', arabicName: 'الفيل', englishName: 'The Elephant', englishNameTranslation: 'The Elephant', numberOfAyahs: 5, revelationType: 'Meccan' },
    { number: 106, name: 'Quraysh', arabicName: 'قريش', englishName: 'Quraysh', englishNameTranslation: 'Quraysh', numberOfAyahs: 4, revelationType: 'Meccan' },
    { number: 107, name: 'Al-Ma\'un', arabicName: 'الماعون', englishName: 'The Small Kindnesses', englishNameTranslation: 'The Small Kindnesses', numberOfAyahs: 7, revelationType: 'Meccan' },
    { number: 108, name: 'Al-Kawthar', arabicName: 'الكوثر', englishName: 'The Abundance', englishNameTranslation: 'The Abundance', numberOfAyahs: 3, revelationType: 'Meccan' },
    { number: 109, name: 'Al-Kafirun', arabicName: 'الكافرون', englishName: 'The Disbelievers', englishNameTranslation: 'The Disbelievers', numberOfAyahs: 6, revelationType: 'Meccan' },
    { number: 110, name: 'An-Nasr', arabicName: 'النصر', englishName: 'The Help', englishNameTranslation: 'The Help', numberOfAyahs: 3, revelationType: 'Medinan' },
    { number: 111, name: 'Al-Masad', arabicName: 'المسد', englishName: 'The Palm Fiber', englishNameTranslation: 'The Palm Fiber', numberOfAyahs: 5, revelationType: 'Meccan' },
    { number: 112, name: 'Al-Ikhlas', arabicName: 'الإخلاص', englishName: 'The Sincerity', englishNameTranslation: 'The Purity', numberOfAyahs: 4, revelationType: 'Meccan' },
    { number: 113, name: 'Al-Falaq', arabicName: 'الفلق', englishName: 'The Daybreak', englishNameTranslation: 'The Daybreak', numberOfAyahs: 5, revelationType: 'Meccan' },
    { number: 114, name: 'An-Nas', arabicName: 'الناس', englishName: 'Mankind', englishNameTranslation: 'Mankind', numberOfAyahs: 6, revelationType: 'Meccan' },
];

/**
 * Get Surah by number
 */
export function getSurahByNumber(number: number): Surah | undefined {
    return SURAHS.find(surah => surah.number === number);
}

/**
 * Search Surahs by name
 */
export function searchSurahs(query: string): Surah[] {
    const lowerQuery = query.toLowerCase();
    return SURAHS.filter(surah =>
        surah.name.toLowerCase().includes(lowerQuery) ||
        surah.englishName.toLowerCase().includes(lowerQuery) ||
        surah.arabicName.includes(query)
    );
}
